# MySQL.  Versions 4.1 and 5.0 are recommended.
#
#
# Be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development: 
  adapter: mysql
  username: root
  database: blondet_development
  host: localhost
  password: 
  
production: 
  adapter: mysql
  username: root
  database: game_production
  host: localhost
  password: 
